LIB_DIR = lib
OBJ_DIR = obj

OBJS = obj/defs.o obj/String.o obj/Object.o obj/EventBus.o obj/Event.o obj/CRC32.o \
	   obj/Buffer.o obj/FileInputStream.o obj/FileOutputStream.o obj/Stream.o \
	   obj/InAddr.o obj/Socket.o obj/Channel.o obj/Manager.o

EXAMPLES = examples/event_bus examples/udp_client examples/udp_server

CC = clang++
CCFLAGS = -Qunused-arguments -Wno-format-security -fcolor-diagnostics -fansi-escape-codes -Wno-format -std=c++17 \
		  -Iinclude -Llib -O1 -Wl,-s -static -pthread -static-libstdc++ -static-libgcc -Wno-switch -g

vpath %.cpp src:src/crypto:src/events:src/io:src/net:src/utils:examples

obj/%.o: %.cpp
	@echo [90m - [96m$<[0m
	@$(CC) $(CCFLAGS) -c -o $@ $<

examples/%: %.cpp
	@echo [90m - [96m$<[0m
	@$(CC) $(CCFLAGS) $< -o $@ -lasr

build: lib
all: clean lib

clean:
	@echo [97mCleaning ... [0m
	@rm -rf $(LIB_DIR)
	@rm -rf $(OBJ_DIR)

obj-folder:
	@mkdir -p $(OBJ_DIR)

lib-folder:
	@mkdir -p $(LIB_DIR)

msg-1:
	@echo [97mCompiling sources ... [0m

lib: obj-folder lib-folder msg-1 $(OBJS)
	@echo [97mBuilding library ... [0m
	@rm -rf $(LIB_DIR)\libasr.a
	@ar rcs $(LIB_DIR)/libasr.a $(OBJS)

msg-2:
	@echo [97mBulding examples ... [0m

examples: msg-2 $(EXAMPLES)
	@echo [97mDone[0m

# Build and run examples
event_bus: examples/event_bus
	@$<
udp_server: examples/udp_server
	@$<
udp_client: examples/udp_client
	@$<
tcp_server: examples/tcp_server
	@$<
tcp_client: examples/tcp_client
	@$<
custom_protocol_client: examples/custom_protocol
	@$< client
custom_protocol_server: examples/custom_protocol
	@$< server
